function fmt(min) {
  let m = ((min % 1440) + 1440) % 1440;
  const h = Math.floor(m / 60);
  const mm = m % 60;
  return String(h).padStart(2, "0") + ":" + String(mm).padStart(2, "0");
}

export async function exportBreaksPdf(schedule) {
  const { jsPDF } = await import("jspdf");

  const breaks = [...(schedule.breaks || [])].sort(
    (a, b) => (a.start_minutes ?? 0) - (b.start_minutes ?? 0)
  );
  const doc = new jsPDF({ orientation: "landscape", unit: "pt", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 28;
  const date = schedule.schedule_date || "";

  doc.setFont("helvetica", "bold");
  doc.setFontSize(16);
  doc.text("Break Roster" + (date ? " — " + date : ""), margin, margin + 8);

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const sum = schedule.summary || {};
  doc.text(
    [
      `Staff: ${sum.total_staff ?? breaks.length}`,
      `Breaks: ${sum.total_breaks ?? breaks.length}`,
      `Covered: ${sum.covered ?? 0}`,
      `Flagged: ${sum.flagged ?? 0}`,
    ].join("   •   "),
    margin,
    margin + 24
  );

  const cols = [
    { title: "Time", x: margin, w: 70 },
    { title: "Dur", x: margin + 70, w: 34 },
    { title: "Team member", x: margin + 104, w: 120 },
    { title: "Area", x: margin + 224, w: 120 },
    { title: "Cover", x: margin + 344, w: 150 },
    { title: "Status", x: margin + 494, w: pageW - margin - 494 },
  ];

  let y = margin + 44;
  doc.setFillColor(240, 240, 240);
  doc.rect(margin, y - 12, pageW - margin * 2, 18, "F");
  doc.setFont("helvetica", "bold");
  doc.setFontSize(9);
  cols.forEach((c) => doc.text(c.title, c.x, y));
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const rowH = 16;
  const maxY = doc.internal.pageSize.getHeight() - margin;

  breaks.forEach((b, i) => {
    if (y + rowH > maxY) {
      doc.addPage();
      y = margin + 8;
      doc.setFillColor(240, 240, 240);
      doc.rect(margin, y - 12, pageW - margin * 2, 18, "F");
      doc.setFont("helvetica", "bold");
      cols.forEach((c) => doc.text(c.title, c.x, y));
      y += 8;
      doc.setFont("helvetica", "normal");
    }
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 250);
      doc.rect(margin, y - 11, pageW - margin * 2, rowH, "F");
    }
    const time = `${fmt(b.start_minutes)} – ${fmt(b.end_minutes)}`;
    const dur = `${b.duration}m`;
    const statusLabel =
      b.status === "covered"
        ? "Covered"
        : b.status === "self-managed"
        ? "Self-managed"
        : b.status === "unassigned"
        ? "Needs cover"
        : "Flagged";
    const cover = b.cover ? `${b.cover}${b.cover_area ? " (" + b.cover_area + ")" : ""}` : "—";
    doc.setTextColor(33, 33, 33);
    doc.text(time, cols[0].x, y);
    doc.text(dur, cols[1].x, y);
    doc.text(String(b.team_member || "").slice(0, 20), cols[2].x, y);
    doc.text(String(b.area || "").slice(0, 18), cols[3].x, y);
    doc.text(String(cover).slice(0, 26), cols[4].x, y);
    if (b.status === "covered") doc.setTextColor(4, 120, 87);
    else if (b.status === "self-managed") doc.setTextColor(2, 132, 199);
    else if (b.status === "unassigned") doc.setTextColor(100, 116, 139);
    else doc.setTextColor(180, 83, 9);
    doc.text(statusLabel, cols[5].x, y);
    y += rowH;
  });

  doc.setTextColor(150, 150, 150);
  doc.setFontSize(8);
  doc.text("Generated by ShiftShift", margin, doc.internal.pageSize.getHeight() - 12);

  const fileName = `break-roster${date ? "-" + date : ""}.pdf`;
  doc.save(fileName);
}